stages:
  - build
  - end-to-end-tests
  - deploy

variables:
  DOMAIN: ""
  DB_USER: user
  DB_PASSWORD: password
  DB_ROOT_PASSWORD: rootpassword
  DB_NAME: kanclOnline
  CYPRESS_baseUrl: http://app:$8080

build:
  stage: build
  image: maven:3.8.6-openjdk-11
  script:
    - mvn test
    - mvn package
  artifacts:
    untracked: false
    expire_in: 1 day
    paths:
      - target/server-1.0-SNAPSHOT.jar

end-to-end-tests:
  stage: end-to-end-tests
  image: docker:20.10.17
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:20.10.17-dind
  
  script:
    - docker volume create --name=sql_data
    - docker volume create --name=caddy_data
    - apk add docker-compose
    - cd run
    - docker-compose -f docker-compose.yml -f docker-compose-test.yml up --build --exit-code-from cypress
    - cd ..
  artifacts:
    untracked: false
    expire_in: 4 hours
    when: on_failure
    paths:
      - src/test/cypress/screenshots
      - src/test/cypress/videos

deploy:
  stage: deploy
  only: ["main"]
  image: alpine
  before_script:
    - apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

  script:
    - rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete . deployer@kancl.online:/opt/kancl.online
    - ssh -v -o StrictHostKeyChecking=no deployer@kancl.online "cd /opt/kancl.online; ./run/deploy.sh"
