stages:
  - end-to-end-tests
  - deploy

variables:
  HTTP_PORT: 8080
  HTTPS_PORT: 8081
  DOMAIN: ""
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: kanclOnline
  CYPRESS_baseUrl: http://app:$8080

end-to-end-tests:
  stage: end-to-end-tests

  services:
    - name: jansimonek/caddy-maria-java:0.1.1
      alias: app
      command:
        - /bin/bash
        - -c
        - |
          pwd &&
          ls
      entrypoint: [""]

  image:
    name: cypress/included:10.3.0
    entrypoint: [""]

  script:
    - cp -r test/* /test
    - cd /test
    - cypress run

deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."