version: "3.7"

services:
  db:
    image: mariadb:10.7
    restart: unless-stopped

    environment:
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "password"
      MARIADB_ROOT_PASSWORD: "rootpassword"
      MARIADB_DATABASE: "kanclOnline"

    volumes:
      - type: bind
        source: ./sql
        target: /docker-entrypoint-initdb.d
        read_only: true
      - sql_data:/var/lib/mysql

volumes:
  sql_data:
    external: true
