version: "3.2"

services:
    server:
        build:
            context: .
            dockerfile: server.Dockerfile
        container_name: server
        restart: unless-stopped

        depends_on:
            - db
        
        ports:
            - 8080:8080/tcp

        networks:
            net:
                ipv4_address: 10.0.0.2

    db:
        image: mariadb:10.7
        container_name: db
        restart: unless-stopped

        networks:
            net:
                ipv4_address: 10.0.0.3

        environment:
            MARIADB_USER: "user"
            MARIADB_PASSWORD: "password"
            MARIADB_ROOT_PASSWORD: "rootpassword"
            MARIADB_DATABASE: "kanclOnline"

        volumes:
            - type: bind
              source: ./sql
              target: /docker-entrypoint-initdb.d
              read_only: true
            - sql_data:/var/lib/mysql


  #   caddy:
  #       # https://hub.docker.com/_/caddy
  #       image: caddy:2.4.6
  #       container_name: caddy
  #       restart: unless-stopped
  #
  #       volumes:
  #           - caddy_data:/data
  #           - caddy_config:/config
  #
  #       healthcheck:
  #           test: ["CMD", "caddy", "version"]
  #
  #       depends_on:
  #           - server
  #
  #       ports:
  #           - "80:80" # For HTTP -> HTTPS redirects
  #           - "443:443"
  #
  #       networks:
  #           net: {}

  # https://hub.docker.com/_/mariadb
  # https://hub.docker.com/r/jenkins/jenkins

volumes:
    caddy_data:
        external: true
    caddy_config:
    sql_data:
        external: true

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
