version: "3"

services:
    server:
        build:
            context: .
            dockerfile: server.Dockerfile
        container_name: server
        restart: unless-stopped
        
        ports:
            - 8080:8080/tcp

        networks:
            net:
                ipv4_address: 10.0.0.2

volumes:
    caddy_data:
        external: true
    caddy_config:

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
