version: "3.7"

services:
    server:
        build:
            context: .
            dockerfile: server.Dockerfile
        restart: unless-stopped

        depends_on:
            - db

        volumes:
            - type: bind
              source: ./web
              target: /usr/app/web
              read_only: true

    caddy:
        # https://hub.docker.com/_/caddy
        build:
            context: .
            dockerfile: caddy.Dockerfile
        restart: unless-stopped

        environment:
          HTTP_PORT: ${HTTP_PORT}
          HTTPS_PORT: ${HTTPS_PORT}
          DOMAIN: ${DOMAIN}

        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfilex
            - caddy_data:/data
            - caddy_config:/config

        healthcheck:
            test: ["CMD", "caddy", "version"]

        depends_on:
            - server

        ports:
            - "${HTTP_PORT}:${HTTP_PORT}/tcp"
            - "${HTTPS_PORT}:${HTTPS_PORT}/tcp"

volumes:
    caddy_data:
        external: true
    caddy_config:
