version: "3.7"

services:
    server:
        build:
            context: .
            dockerfile: server.Dockerfile
        container_name: server
        restart: unless-stopped

        depends_on:
            - db

        networks:
          dbnet:
                ipv4_address: 10.0.0.2

    db:
        image: mariadb:10.7
        container_name: db
        restart: unless-stopped

        networks:
          dbnet:
                ipv4_address: 10.0.0.3

        environment:
            MARIADB_USER: "user"
            MARIADB_PASSWORD: "password"
            MARIADB_ROOT_PASSWORD: "rootpassword"
            MARIADB_DATABASE: "kanclOnline"

        volumes:
            - type: bind
              source: ./sql
              target: /docker-entrypoint-initdb.d
              read_only: true
            - sql_data:/var/lib/mysql


    caddy:
        # https://hub.docker.com/_/caddy
        build:
            context: .
            dockerfile: caddy.Dockerfile
        container_name: caddy
        restart: unless-stopped

        environment:
          HTTP_PORT: ${HTTP_PORT}
          HTTPS_PORT: ${HTTPS_PORT}
          DOMAIN: ${DOMAIN}

        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfilex
            - caddy_data:/data
            - caddy_config:/config

        healthcheck:
            test: ["CMD", "caddy", "version"]

        depends_on:
            - server

        ports:
            - "${HTTP_PORT}:${HTTP_PORT}/tcp"
            - "${HTTPS_PORT}:${HTTPS_PORT}/tcp"

  # https://hub.docker.com/_/mariadb
  # https://hub.docker.com/r/jenkins/jenkins

volumes:
    caddy_data:
        external: true
    caddy_config:
    sql_data:
        external: true

networks:
  dbnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
