#!/usr/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# exit script on first error
set -e

docker container prune

echo -e ""
echo -e "${GREEN}Running tests${NC}"
echo -e ""
(export HTTP_PORT=8080; export HTTPS_PORT=8081; export DOMAIN=''; docker-compose -f docker-compose.yml -f test/docker-compose.test.yml up --build --exit-code-from cypress)

echo -e ""
echo -e "${GREEN}Deploying${NC}"
echo -e ""
docker-compose up --build
