#!/usr/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# exit script on first error
set -e

echo -e ""
echo -e "${GREEN}Running tests${NC}"
echo -e ""
(export HTTP_PORT=8080; export HTTPS_PORT=8081; export DOMAIN=''; docker-compose -f docker-compose.yml -f test/docker-compose.test.yml -p test up --build --exit-code-from cypress)


echo -e ""
echo -e "${GREEN}Deploying${NC}"
echo -e ""

mkdir -p /opt/kancl.online
rm -rf /opt/kancl.online
mkdir -p /opt/kancl.online
cp -R . /opt/kancl.online/
cd /opt/kancl.online

docker-compose -f docker-compose.yml -f db-docker-compose.yml down
docker container prune -f
docker-compose -f docker-compose.yml -f db-docker-compose.yml up --build --detach
