#!/usr/bin/bash

# exit script on first error
set -e

# create temp directory and clean it up on exit
TEMP_DIR=`mktemp -d`
clean_up () {
    ARG=$?
    rm -rf "$TEMP_DIR"
    exit $ARG
}
trap clean_up EXIT

# for each received branch
while read oldrev newrev ref
do
	if [[ $ref =~ .*/main ]];
	then
		echo "Received update to branch $ref. Deploying..."

		# check it out in temp directory
		git "--work-tree=$TEMP_DIR" checkout -f

		# cd into it
		cd $TEMP_DIR

		# build it
		cd run
		./test_and_deploy
	else
		echo "Only branch main will be deployed on this server, received $ref."
	fi
done
