version: "3.7"

services:
  caddy:
    image: caddy:2.5.2-alpine
    restart: unless-stopped

    depends_on:
      - kanclonline

    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

    environment:
      CADDY_ADDRESS: "http://"

    ports:
      - "8080:80/tcp"

  kanclonline:
    image: amazoncorretto:17.0.4-alpine3.15
    restart: unless-stopped

    volumes:
      - type: bind
        source: ../target
        target: /usr/app/target
        read_only: true
      - type: bind
        source: ../web
        target: /usr/app/web
        read_only: true
      - type: bind
        source: ../src
        target: /usr/app/src
        read_only: true
      - sql_data:/usr/app/db

    environment:
      ZOOM_VERIFICATION_TOKEN: ${ZOOM_VERIFICATION_TOKEN}

    entrypoint: ["java", "-jar", "/usr/app/target/server-1.0-SNAPSHOT.jar"]
    working_dir: /usr/app

volumes:
  caddy_data:
    external: true
  caddy_config:
  sql_data:
    external: true
