version: "3.7"

services:
  kanclonline:
    build:
      context: ..
      dockerfile: run/Dockerfile
    restart: unless-stopped

    volumes:
      - type: bind
        source: ../target
        target: /usr/app/target
        read_only: true
      - type: bind
        source: ../web
        target: /usr/app/web
        read_only: true
      - type: bind
        source: ../src
        target: /usr/app/src
        read_only: true
      - type: bind
        source: ../sql
        target: /docker-entrypoint-initdb.d/
        read_only: true
      - caddy_data:/data
      - caddy_config:/config
      - sql_data:/usr/app/db

    environment:
      CADDY_ADDRESS: "http://"
      ZOOM_VERIFICATION_TOKEN: ${ZOOM_VERIFICATION_TOKEN}
      # environment variables read by kancl.online Java app:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      # environment variables ready by DB:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677

    ports:
      - "8080:80/tcp"


volumes:
  caddy_data:
    external: true
  caddy_config:
  sql_data:
    external: true
