version: "3.7"

services:
    app:
        build:
            context: ..
            dockerfile: ./Dockerfile
        restart: unless-stopped

        volumes:
            - type: bind
              source: ../web
              target: /usr/app/web
              read_only: true
            - caddy_data:/data
            - caddy_config:/config

        ports:
            - "${HTTP_PORT}:${HTTP_PORT}/tcp"
            - "${HTTPS_PORT}:${HTTPS_PORT}/tcp"

volumes:
    caddy_data:
        external: true
    caddy_config:
