name: test-on-push
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker-compose -f docker-compose.yml -f test/docker-compose.test.yml up --build --exit-code-from cypress
